# -*- coding: utf-8 -*-
"""income.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gR4qdue1CU-tsLXQbMsnJODjubPfT2AR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

data=pd.read_csv("income.csv")

data

data.info()

data.isna().sum()

data.isna().sum().sum()

data.describe()

data.count()



df.shape

df.dtypes

df.columns

data.head(2)

"""Feature Engineering

"""

df.Bachelors=df.Bachelors.replace(['HS-grad','Bachelors'])
df.Bachelors=df.Bachelors.replace(['Masters','grad'])
df.Bachelors=df.Bachelors.replace(['Doctorate','doc'])



